import { describe, expect, it } from 'vitest';
import {
  configurationHash,
  credentialsMatch,
  generateCredential,
  hashCredential,
  looksLike,
  stripVolatileHeader,
} from './agentAuth.js';

const artefact = (path: string, content: string) => ({
  path,
  content,
  mode: '0640',
  owner: 'root',
  group: 'proxy',
});

describe('agent credentials', () => {
  it('generates prefixed credentials and stores only the hash', () => {
    const enrollment = generateCredential('enrollment');
    const agent = generateCredential('agent');
    expect(looksLike('enrollment', enrollment.plaintext)).toBe(true);
    expect(looksLike('agent', agent.plaintext)).toBe(true);
    expect(looksLike('agent', enrollment.plaintext)).toBe(false);
    expect(enrollment.hash).not.toContain(enrollment.plaintext);
    expect(enrollment.hash).toHaveLength(64);
  });

  it('produces a different credential every time', () => {
    expect(generateCredential('agent').plaintext).not.toBe(generateCredential('agent').plaintext);
  });

  it('hashes deterministically and ignores surrounding whitespace', () => {
    const { plaintext, hash } = generateCredential('agent');
    expect(hashCredential(plaintext)).toBe(hash);
    expect(hashCredential(`  ${plaintext}\n`)).toBe(hash);
  });

  it('compares without leaking length differences through an exception', () => {
    expect(credentialsMatch('abc', 'abc')).toBe(true);
    expect(credentialsMatch('abc', 'abcd')).toBe(false);
  });
});

describe('configuration hash', () => {
  /*
   * Regression: the generated header carries a compile timestamp. While it was
   * part of the hash, no node ever counted as in sync and every agent poll
   * rewrote the configuration and reconfigured Squid.
   */
  it('is stable across compilations of the same policy', () => {
    const first = '# Generated by SCP\n# Generated:  2026-08-16T10:00:00.000Z\nhttp_access deny all\n';
    const second = '# Generated by SCP\n# Generated:  2026-08-16T11:30:00.000Z\nhttp_access deny all\n';
    expect(configurationHash(first, [])).toBe(configurationHash(second, []));
  });

  it('changes when the policy changes', () => {
    const allow = '# Generated:  x\nhttp_access allow all\n';
    const deny = '# Generated:  x\nhttp_access deny all\n';
    expect(configurationHash(allow, [])).not.toBe(configurationHash(deny, []));
  });

  it('covers artefact content, mode and ownership', () => {
    const base = [artefact('/etc/squid/scp/local_users', 'alice:$6$a$b\n')];
    const changedContent = [artefact('/etc/squid/scp/local_users', 'bob:$6$a$b\n')];
    const changedOwner = [{ ...base[0]!, group: 'root' }];
    const changedMode = [{ ...base[0]!, mode: '0600' }];

    expect(configurationHash('conf', base)).not.toBe(configurationHash('conf', changedContent));
    expect(configurationHash('conf', base)).not.toBe(configurationHash('conf', changedOwner));
    expect(configurationHash('conf', base)).not.toBe(configurationHash('conf', changedMode));
  });

  it('does not depend on artefact order', () => {
    const a = artefact('/a', 'one');
    const b = artefact('/b', 'two');
    expect(configurationHash('conf', [a, b])).toBe(configurationHash('conf', [b, a]));
  });

  it('keeps every non-timestamp comment', () => {
    expect(stripVolatileHeader('# Adapter: squid-6\n# Generated:  now\nx')).toBe('# Adapter: squid-6\nx');
  });
});
